### ISSUE TITLE
Versioned redirects

### ISSUE THREAD

**Issue by neersighted** [rust-lang-nursery/rust-lang-nursery.github.io#1]
I just wanted to note that creating redirects for each of the versions in https://github.com/rust-lang/rust-clippy/tree/gh-pages (past versions only, of course, as new versions of Clippy should have the new URL) would be quite helpful, as currently any versioned Clippy links are broken.

**Comment by phansch** [comment]
Yea, that makes sense IMO. I added the redirect for the latest version for now in #2 

If someone wants to add the redirects for the remaining versions, they can be found here in JSON format: https://github.com/rust-lang/rust-clippy/blob/gh-pages/versions.json.

It would also be nice if each redirect page redirects to the specific docs for the requested version instead of https://rust-lang.github.io/rust-clippy/.

cc https://github.com/rust-lang/rust-clippy/issues/3454
